In [17]:
!pip install mathutils

     ---------------------------------------- 0.0/245.4 kB ? eta -:--:--
     --- --------------------------------- 20.5/245.4 kB 330.3 kB/s eta 0:00:01
     -------------- ------------------------ 92.2/245.4 kB 1.1 MB/s eta 0:00:01
     -------------------------------------- 245.4/245.4 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for mathutils: filename=mathutils-3.3.0-cp312-cp312-win_amd64.whl size=102447 sha256=0f7bf595a268a2cd6a90f87c67479623b9927b0315e1c18d5245b9ff3afcb304
  Stored in directory: c:\users\rohan\appdata\local\pip\cache\wheels\19\2b\c3\58bd22ea2e13b8d8d882bfa0cf6ccad0d7028cd6f22fa5015e
Successfully built mathutils


In [2]:
import os
import numpy as np
from tqdm import tqdm

from plyfile import PlyData, PlyElement
import mathutils

In [3]:
scene_path = "C:\\Users\\rohan\\Documents\\sp24\\cs280\\final_proj\\output_poster_blender.ply"
with open(scene_path, "rb") as f:
    scene_cloud = PlyData.read(f)

In [4]:
scene_cloud.elements[0].data.dtype.names

('x',
 'y',
 'z',
 'nx',
 'ny',
 'nz',
 'f_dc_0',
 'f_dc_1',
 'f_dc_2',
 'f_rest_0',
 'f_rest_1',
 'f_rest_2',
 'f_rest_3',
 'f_rest_4',
 'f_rest_5',
 'f_rest_6',
 'f_rest_7',
 'f_rest_8',
 'f_rest_9',
 'f_rest_10',
 'f_rest_11',
 'f_rest_12',
 'f_rest_13',
 'f_rest_14',
 'f_rest_15',
 'f_rest_16',
 'f_rest_17',
 'f_rest_18',
 'f_rest_19',
 'f_rest_20',
 'f_rest_21',
 'f_rest_22',
 'f_rest_23',
 'f_rest_24',
 'f_rest_25',
 'f_rest_26',
 'f_rest_27',
 'f_rest_28',
 'f_rest_29',
 'f_rest_30',
 'f_rest_31',
 'f_rest_32',
 'f_rest_33',
 'f_rest_34',
 'f_rest_35',
 'f_rest_36',
 'f_rest_37',
 'f_rest_38',
 'f_rest_39',
 'f_rest_40',
 'f_rest_41',
 'f_rest_42',
 'f_rest_43',
 'f_rest_44',
 'opacity',
 'scale_0',
 'scale_1',
 'scale_2',
 'rot_0',
 'rot_1',
 'rot_2',
 'rot_3')

In [5]:
np.mean(scene_cloud.elements[0]["scale_0"])

-6.77354

In [6]:
xyz = np.stack((np.asarray(scene_cloud.elements[0]["x"]),
                np.asarray(scene_cloud.elements[0]["y"]),
                np.asarray(scene_cloud.elements[0]["z"])), axis=1)

N = len(xyz)

log_scales = np.stack((np.asarray(scene_cloud.elements[0]["scale_0"]),
                    np.asarray(scene_cloud.elements[0]["scale_1"]),
                    np.asarray(scene_cloud.elements[0]["scale_2"])), axis=1)

scales = np.exp(log_scales)

quats = np.stack((np.asarray(scene_cloud.elements[0]["rot_0"]),
                    np.asarray(scene_cloud.elements[0]["rot_1"]),
                    np.asarray(scene_cloud.elements[0]["rot_2"]),
                    np.asarray(scene_cloud.elements[0]["rot_3"])), axis=1)

rots_euler = np.zeros((N, 3))

for i in range(N):
    quat = mathutils.Quaternion(quats[i].tolist())
    euler = quat.to_euler()
    rots_euler[i] = (euler.x, euler.y, euler.z)

In [7]:
np.mean(xyz, axis=0)

array([-0.3717013 , -0.21717648,  0.05315011], dtype=float32)

In [30]:
print(len(scene_cloud["vertex"]))
for i in tqdm(range(len(scene_cloud["vertex"]))):
    if i % 500 == 0:
        print(scales[i], xyz[i], rots_euler[i])

299950


100%|██████████| 299950/299950 [00:00<00:00, 2202427.21it/s]

[1.7359916e-05 2.2013579e-03 5.0159278e-03] [-0.13979992 -0.02797761 -0.55777526] [ 0.7800681  -0.99728376 -1.15808713]
[6.2415865e-04 2.6080686e-05 1.6223398e-03] [-0.0233979   0.15610795 -0.1260912 ] [ 0.53615433  0.78661817 -1.549402  ]
[1.0865056e-03 5.3682412e-05 9.1404170e-03] [-0.05762223  0.09456691 -0.13710232] [2.48174119 0.86389822 1.06142199]
[0.00385475 0.00050358 0.00239193] [-0.12957059 -0.08598    -0.15249951] [-1.15808022 -2.09711242 -0.27362275]
[0.00010093 0.00209626 0.02264188] [-0.35338506  0.31882155 -0.22148776] [-1.65729415 -2.35528541 -0.44526052]
[0.00444302 0.01097753 0.00389004] [-0.23754981  0.2072994  -0.2158858 ] [-1.18142855 -1.22791612 -0.61577374]
[0.00534678 0.00798058 0.00995333] [-0.5505484  -0.2877949  -0.59661365] [-1.63833678 -0.05399981 -1.11690879]
[0.0220936  0.00538828 0.0029656 ] [ 0.2502358  -0.3481763  -0.60898143] [ 1.88694298  0.25872999 -2.25760579]
[0.03423928 0.01289845 0.18447606] [-0.579294   3.6482878  0.8400738] [-0.13158034  0.73